// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// All values resolve at PM2-load time, not generation time:
//   - INSTANCE honors CTX_INSTANCE_ID from the calling shell, so
//     `CTX_INSTANCE_ID=foo pm2 restart cortextos-daemon` switches instances
//     without regenerating;
//   - CTX_ROOT derives from the EFFECTIVE instance (no split-state when only
//     CTX_INSTANCE_ID is set);
//   - ROOT derives from __dirname, so the file survives a moved checkout or new host.
const path = require('path');
const os = require('os');
const INSTANCE = process.env.CTX_INSTANCE_ID || "default";
const ROOT = __dirname;
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: path.join(ROOT, 'dist', 'daemon.js'),
      args: '--instance ' + INSTANCE,
      cwd: ROOT,
      env: {
        CTX_INSTANCE_ID: INSTANCE,
        CTX_ROOT: process.env.CTX_ROOT || path.join(os.homedir(), '.cortextos', INSTANCE),
        CTX_FRAMEWORK_ROOT: ROOT,
        CTX_PROJECT_ROOT: ROOT,
        CTX_ORG: process.env.CTX_ORG || "korendigital",
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
